### ISSUE TITLE
What to config?

### ISSUE THREAD

**Issue by f1r3walled** [kevthehermit/PasteHunter#33]
Hello,
Sorry for the stupid question, but it is not so clear to me what to change in the settings.json. I followed some tutorials on TechAnarchy but I'm really not understanding.
I have a Pastebin Pro account, too.
See my output while executing it:
user@server:/opt/pastehunter$ sudo python3 pastehunter.py
INFO:pastehunter.py:Starting PasteHunter Version: 0.1
INFO:pastehunter.py:Reading Configs
ERROR:pastehunter.py:Log Level not in config file. Update your base config file!
INFO:pastehunter.py:Setting Log Level to 20
INFO:pastehunter.py:Configure Inputs
INFO:pastehunter.py:Enabled Input: pastebin
INFO:pastehunter.py:Enabled Input: gists
INFO:pastehunter.py:Enabled Input: dumpz
INFO:pastehunter.py:Configure Outputs
INFO:pastehunter.py:Enabled Output: elastic_output
INFO:pastehunter.py:Compile Yara Rules
INFO:pastehunter.py:Enable Blacklist Rules
INFO:pastehunter.py:Populating Queue
INFO:pastehunter.py:Fetching paste list from inputs.pastebin
ERROR:pastebin.py:Unable to parse paste results: Expecting value: line 1 column 1 (char 0)
INFO:pastehunter.py:Fetching paste list from inputs.gists
INFO:gists.py:Remaining Limit: 54. Resets at 2018-05-04T18:41:44
ERROR:gists.py:Auth Failed
INFO:pastehunter.py:Fetching paste list from inputs.dumpz
INFO:pastehunter.py:Sleeping for 300 Seconds

I have manually and successfully installed Elastic Search, Kibana, Logstash and Yara.
Can you advise me, please?

Thank you!

**Comment by kevthehermit** [comment]
The log error was because i missed a line in the sample config file. 
You can add ```"logging_level": 20``` under general in settings.json to fix this. 

The parse error is usually caused because you have not whitelisted your IP address. 

If you visit https://scrape.pastebin.com/api_scraping.php in a browser you should see a json array of paste details or an error message

For gists you need to add a gist API key. - https://github.com/kevthehermit/PasteHunter#github

I will add some more error logging to identify issues with the pastebin API

**Comment by f1r3walled** [comment]
Great! Now it is fine and I just need to adjust my Elastic Search index patterns!
There is no more errors!
Thank you so much!

**Comment by Laurenttpp** [comment]
@f1r3walled Did you manage to add a gist API Key? If yes, how did you do it?

Thank You
